global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1

scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090

- job_name: 'docker'
  static_configs:
  - targets: 
    - host.docker.internal:9323

- job_name: 'postgres'
  static_configs:
  - targets:
    - pg-exporter:9187
  
- job_name: 'actors'
  scrape_interval: 5s
  scrape_timeout: 4s
  static_configs:
  - targets:
    - host.docker.internal:1235
  
- job_name: 'locks'
  scrape_interval: 5s
  scrape_timeout: 4s
  static_configs:
  - targets:
    - host.docker.internal:1234

- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8080